---
- name: Stop scanning module services
  hosts: scanner
  roles:
    - stopservices
  tags:
    - cleanup
    - stopservices

- name: Clean saasherder and its residues from system
  hosts: scanner
  roles:
    - cleansaasherder
  tags:
    - cleanup
    - cleansaasherder

