---
- name: Run beanstalkd server container
  docker_container:
      name: beanstalkd_server
      image: scanning/beanstalkd:rhel7
      state: started
      restart: yes
      restart_policy: unless-stopped
      detach: yes
      ports:
       - "0.0.0.0:11300:11300/tcp"
  become: true
  tags:
    - services
    - beanstalkd

- name: Copy systemd service files for services in scanning
  copy: src="{{ role_path }}/../../../scripts/{{ item }}" dest=/etc/systemd/system/ mode=u+x
  with_items:
      - dispatcher-worker.service
      - scan-worker.service
      - notify-worker.service
  become: true
  tags: services
  register: service_files_updated

- name: Reload systemctl daemon
  shell: systemctl daemon-reload
  become: true
  when: service_files_updated
  tags: services

- name: Enable and start services
  service: name={{ item }} state=restarted enabled=yes
  with_items:
      - dispatcher-worker.service
      - scan-worker.service
      - notify-worker.service
  become: true
  tags: services
